SELECT p.PRODUCT_CODE, 
        sum(o.SALES_AMOUNT) * p.PRICE as 'SALES'
from PRODUCT p INNER JOIN OFFLINE_SALE o on p.PRODUCT_ID = o.PRODUCT_ID
group by o.PRODUCT_ID
order by SALES DESC, PRODUCT_CODE ASC