SELECT substr(SALES_DATE, 1, 10) as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
    select SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    from ONLINE_SALE
    UNION
    select SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
    from OFFLINE_SALE
) A
where SALES_DATE between '2022-03-01' AND '2022-03-31'
order by SALES_DATE, PRODUCT_ID, USER_ID