SELECT i.ANIMAL_ID, i.NAME
from ANIMAL_INS i INNER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
where if(i.ANIMAL_ID = o.ANIMAL_ID, DATEDIFF(o.DATETIME, i.DATETIME), null)
order by DATEDIFF(o.DATETIME, i.DATETIME) DESC
LIMIT 2
