SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
from ANIMAL_INS i INNER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
where i.SEX_UPON_INTAKE != o.SEX_UPON_OUTCOME
group by i.ANIMAL_ID
order by ANIMAL_ID ASC