SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, ROUND(AVG(r.REVIEW_SCORE),2) as "SCORE"
from REST_INFO i INNER JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID
where i.ADDRESS like "서울%"
group by i.REST_ID
order by SCORE DESC, i.FAVORITES DESC