SELECT YEAR(o.SALES_DATE) as "YEAR", 
        MONTH(o.SALES_DATE) as "MONTH",
        u.GENDER,
        COUNT(DISTINCT o.USER_ID) AS USERS
from USER_INFO u INNER JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
where u.GENDER is not null
GROUP BY YEAR, MONTH, u.GENDER
order by YEAR ASC , MONTH ASC, u.GENDER ASC
