WITH TOTAL AS(
SELECT *
FROM USER_INFO
WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)

select YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH,
       count(DISTINCT o.USER_ID) as PURCHASED_USERS,
       round(count(DISTINCT o.USER_ID) / (select count(*) from TOTAL), 1) as PUCHASED_RATIO
from USER_INFO u JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
where YEAR(JOINED) = 2021
group by YEAR(SALES_DATE), MONTH(SALES_DATE)