SELECT a.PRODUCT_ID, a.PRODUCT_NAME, (a.PRICE * SUM(b.AMOUNT)) as 'TOTAL_SALES'
from FOOD_PRODUCT a INNER JOIN FOOD_ORDER b ON a.PRODUCT_ID = b.PRODUCT_ID
where b.PRODUCE_DATE like '2022-05%'
group by a.PRODUCT_ID
order by TOTAL_SALES DESC, a.PRODUCT_ID ASC