SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, d.MCDP_CD, d.DR_NAME, a.APNT_YMD
from APPOINTMENT a INNER JOIN DOCTOR d on a.MDDR_ID = d.DR_ID INNER JOIN PATIENT p on a.PT_NO = p.PT_NO
where a.APNT_CNCL_YN = 'N' AND a.APNT_YMD like '2022-04-13%' AND a.MCDP_CD like 'CS'
order by a.APNT_YMD ASC