SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) as 'TOTAL_SALES' 
from USED_GOODS_BOARD b INNER JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
where b.STATUS like 'DONE'
group by b.WRITER_ID
HAVING SUM(b.PRICE)>=700000
order by sum(b.PRICE) ASC