SELECT i.ANIMAL_ID, o.NAME
from ANIMAL_INS i INNER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
where if(i.ANIMAL_ID != o.ANIMAL_ID, 0, if(i.DATETIME < o.DATETIME, NULL, 2))
order by i.DATETIME ASC