select MONTH(START_DATE) as MONTH, CAR_ID, count(CAR_ID) as RECORDS
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where START_DATE between '2022-08-01' AND '2022-10-31' AND CAR_ID IN
    (
    select CAR_ID
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    where START_DATE between '2022-08-01' AND '2022-10-31'
    group by CAR_ID
    HAVING count(CAR_ID) >= 5
    )
group by MONTH, CAR_ID
order by MONTH ASC, CAR_ID DESC