SELECT a.CAR_ID
from CAR_RENTAL_COMPANY_CAR a INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID
where CAR_TYPE like '세단' AND MONTH(b.START_DATE) = 10
group by CAR_ID
order by CAR_ID DESC