SELECT i.INGREDIENT_TYPE, sum(if(i.INGREDIENT_TYPE like 'sugar%', f.TOTAL_ORDER, f.TOTAL_ORDER)) as TOTAL_ORDER
from FIRST_HALF f INNER JOIN ICECREAM_INFO i ON f.FLAVOR = i.FLAVOR
group by i.INGREDIENT_TYPE