select CONCAT('/home/grep/src/', BOARD_ID, '/',FILE_ID, FILE_NAME, FILE_EXT) as FILE_PATH
from USED_GOODS_FILE
where BOARD_ID = (
    SELECT BOARD_ID
    from USED_GOODS_BOARD
    order by VIEWS DESC
    LIMIT 1
    )
ORDER BY FILE_ID DESC
