SELECT b.BOOK_ID, a.AUTHOR_NAME, substr(b.PUBLISHED_DATE, 1, 10) as 'PUBLISHED_DATE'
from BOOK b LEFT JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
where b.CATEGORY like '경제'
order by b.PUBLISHED_DATE ASC